<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>

		<!-- Basic Properties -->
		<OutputType>WinExe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<Nullable>enable</Nullable>
		<BuiltInComInteropSupport>true</BuiltInComInteropSupport>
		<AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
		<RootNamespace>DoomMapGuessr</RootNamespace>
		<GenerateDocumentationFile>true</GenerateDocumentationFile>

		<!-- Application manifest for Windows 10 and 11 -->
		<ApplicationManifest>app.manifest</ApplicationManifest>

		<!-- Package Metadata (for Parcel usage) -->
		<Title>DoomMapGuessr</Title>
		<PackageTitle>dev.mf366.doommapguessr</PackageTitle>
		<Authors>Matthew</Authors>
		<ApplicationIcon>..\..\assets\Icon.ico</ApplicationIcon>
		<PackageIcon>..\..\assets\Icon_800x800.png</PackageIcon>
		<PackageReadmeFile>..\..\README.md</PackageReadmeFile>
		<RepositoryUrl>https://github.com/mf366-dev/DoomMapGuessr/</RepositoryUrl>
		<NeutralLanguage>en-US</NeutralLanguage>
		<PackageLicenseFile>..\..\LICENSE.txt</PackageLicenseFile>

		<!-- Used for the actual versioning and Parcel as well -->
		<Version>3.0.0-dev</Version>

		<!--
		Used internally only, for quick Reflection-free version checks
		The last number refers to "revision":
		- 0 if stable
		- 1 if beta/dev/alpha
		-->
		<AssemblyVersion>3.0.0.1</AssemblyVersion>
		<Platforms>AnyCPU;ARM32;ARM64;x64;x86</Platforms>

	</PropertyGroup>


	<!-- Publish AOT if Release -->
	<PropertyGroup Condition="'$(Configuration)' == 'Release'">
		<PublishAot>true</PublishAot>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishTrimmed>true</PublishTrimmed>
		<PublishReadyToRun>false</PublishReadyToRun> <!-- is conflicting with AOT -->
	</PropertyGroup>


	<!-- Don't publish AOT if x86 -->
	<PropertyGroup Condition="'$(Platform)' == 'x86' and '$(Configuration)' == 'Release'">
		<PublishAot>false</PublishAot>
		<PublishSingleFile>true</PublishSingleFile>
		<PublishTrimmed>false</PublishTrimmed>
		<PublishReadyToRun>true</PublishReadyToRun>
	</PropertyGroup>


	<!-- Resources -->
	<ItemGroup>

		<!-- Styles are internal to the project -->
		<AvaloniaResource Include="Styles\**\*">
			<Link>Styles\%(RecursiveDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</AvaloniaResource>

		<!-- Icons are internal to the project -->
		<AvaloniaResource Include="Icons\**\*">
			<Link>Icons\%(RecursiveDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</AvaloniaResource>

		<!-- Assets are external to the project -->
		<AvaloniaResource Include="..\..\assets\**\*">
			<Link>Assets\%(RecursiveDir)%(Filename)%(Extension)</Link>
			<CopyToOutputDirectory>Always</CopyToOutputDirectory>
		</AvaloniaResource>

		<!-- Strings and Resources Setup -->
		<EmbeddedResource Update="Strings\Resources.resx">
			<Generator>PublicResXFileCodeGenerator</Generator>
			<LastGenOutput>Resources.Designer.cs</LastGenOutput>
		</EmbeddedResource>
		<Compile Update="Strings\Resources.Designer.cs">
			<DesignTime>True</DesignTime>
			<AutoGen>True</AutoGen>
			<DependentUpon>Resources.resx</DependentUpon>
		</Compile>

		<!-- Languages must be dependent on neutral strings -->
		<EmbeddedResource Update="Strings\Resources.pt-PT.resx">
			<DependentUpon>Resources.resx</DependentUpon>
		</EmbeddedResource>
		<EmbeddedResource Update="Strings\Resources.pt-br.resx">
			<DependentUpon>Resources.resx</DependentUpon>
		</EmbeddedResource>

	</ItemGroup>


	<!-- Packages -->
	<ItemGroup>

		<!-- Avalonia Base Packages -->
		<PackageReference Include="Avalonia" Version="11.3.13" />
		<PackageReference Include="Avalonia.Desktop" Version="11.3.13" />
		<PackageReference Include="Avalonia.Themes.Fluent" Version="11.3.13" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="11.3.13" />

		<!-- Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration. -->
		<PackageReference Include="Avalonia.Diagnostics" Version="11.3.13">
			<IncludeAssets Condition="'$(Configuration)' != 'Debug'">None</IncludeAssets>
			<PrivateAssets Condition="'$(Configuration)' != 'Debug'">All</PrivateAssets>
		</PackageReference>

		<!-- Condition below is needed to remove Avalonia Accelerate's Diagnostics from build output in Release configuration. -->
		<PackageReference Condition="'$(Configuration)' == 'Debug'" Include="AvaloniaUI.DiagnosticsSupport" Version="2.1.1" />

		<!-- Third-Party packages for Avalonia -->
		<PackageReference Include="ColorTextBlock.Avalonia" Version="11.0.3-a1" />
		<PackageReference Include="Markdown.Avalonia" Version="11.0.3-a1" />

		<!-- Community Toolkit for MVVM -->
		<PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />

		<!-- Data and Others -->
		<PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.5" />
		<PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.5" />
		<PackageReference Include="Octokit" Version="14.0.0" />
		<PackageReference Include="Tmds.DBus.Protocol" Version="0.92.0" />

	</ItemGroup>


	<!-- Projects -->
	<ItemGroup>
		<ProjectReference Include="..\DoomMapGuessr.Common\DoomMapGuessr.Common.csproj" />
		<ProjectReference Include="..\DoomMapGuessr.Data\DoomMapGuessr.Data.csproj" />
		<ProjectReference Include="..\DoomMapGuessr.Services\DoomMapGuessr.Services.csproj" />
	</ItemGroup>


	<!-- Others -->
	<ItemGroup>
		<UpToDateCheckInput Remove="Resources\Fonts.axaml" />
	</ItemGroup>

</Project>
