<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<LangVersion>latest</LangVersion>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<Platforms>AnyCPU;ARM32;ARM64;x64</Platforms>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MSTest" Version="4.2.3" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\src\DoomMapGuessr.App\DoomMapGuessr.App.csproj" />
		<ProjectReference Include="..\src\DoomMapGuessr.Common\DoomMapGuessr.Common.csproj" />
		<ProjectReference Include="..\src\DoomMapGuessr.Data\DoomMapGuessr.Data.csproj" />
		<ProjectReference Include="..\src\DoomMapGuessr.Domain\DoomMapGuessr.Domain.csproj" />
		<ProjectReference Include="..\src\DoomMapGuessr.Services\DoomMapGuessr.Services.csproj" />
	</ItemGroup>

	<ItemGroup>
		<Using Include="Microsoft.VisualStudio.TestTools.UnitTesting" />
	</ItemGroup>

</Project>
