//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DoomMapGuessr.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DoomMapGuessr.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matthew.
        /// </summary>
        public static string App_AuthorName {
            get {
                return ResourceManager.GetString("App.AuthorName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The geo-guessing game of DOOM..
        /// </summary>
        public static string App_ShortDescription {
            get {
                return ResourceManager.GetString("App.ShortDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DoomMapGuessr.
        /// </summary>
        public static string App_Title {
            get {
                return ResourceManager.GetString("App.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Generics_Add {
            get {
                return ResourceManager.GetString("Generics.Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string Generics_Color {
            get {
                return ResourceManager.GetString("Generics.Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coming Soon.
        /// </summary>
        public static string Generics_ComingSoon {
            get {
                return ResourceManager.GetString("Generics.ComingSoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Generics_Edit {
            get {
                return ResourceManager.GetString("Generics.Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language.
        /// </summary>
        public static string Generics_Language {
            get {
                return ResourceManager.GetString("Generics.Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No connection available.
        /// </summary>
        public static string Generics_NoInternet {
            get {
                return ResourceManager.GetString("Generics.NoInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string Generics_Remove {
            get {
                return ResourceManager.GetString("Generics.Remove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove All.
        /// </summary>
        public static string Generics_RemoveAll {
            get {
                return ResourceManager.GetString("Generics.RemoveAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retry.
        /// </summary>
        public static string Generics_Retry {
            get {
                return ResourceManager.GetString("Generics.Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Generics_Save {
            get {
                return ResourceManager.GetString("Generics.Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Brave yet foolish..
        /// </summary>
        public static string Greetings_CreepyHour01 {
            get {
                return ResourceManager.GetString("Greetings.CreepyHour01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello, world!.
        /// </summary>
        public static string Greetings_HelloWorld {
            get {
                return ResourceManager.GetString("Greetings.HelloWorld", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ready to start guessing?.
        /// </summary>
        public static string Greetings_Regular01 {
            get {
                return ResourceManager.GetString("Greetings.Regular01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These screenshots won&apos;t guess themselves....
        /// </summary>
        public static string Greetings_Regular02 {
            get {
                return ResourceManager.GetString("Greetings.Regular02", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cozy sunset, cozy guessing!.
        /// </summary>
        public static string Greetings_Sunset01 {
            get {
                return ResourceManager.GetString("Greetings.Sunset01", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achievements &amp; Items.
        /// </summary>
        public static string Menu_Achievements {
            get {
                return ResourceManager.GetString("Menu.Achievements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Classic Mode.
        /// </summary>
        public static string Menu_ClassicMode {
            get {
                return ResourceManager.GetString("Menu.ClassicMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Menu_Home {
            get {
                return ResourceManager.GetString("Menu.Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Precision Mode.
        /// </summary>
        public static string Menu_PrecisionMode {
            get {
                return ResourceManager.GetString("Menu.PrecisionMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Menu_Settings {
            get {
                return ResourceManager.GetString("Menu.Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legacy of Rust joins the alignment!.
        /// </summary>
        public static string News_LegacyOfRustNew {
            get {
                return ResourceManager.GetString("News.LegacyOfRustNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The latest WAD to be developed by id Software joins the alignment of guessable WADs in this major DoomMapGuessr update!
        ///What are you waiting for?
        ///Start guessing now!.
        /// </summary>
        public static string News_LegacyOfRustNew_Description {
            get {
                return ResourceManager.GetString("News.LegacyOfRustNew.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to See on GitHub.
        /// </summary>
        public static string News_SeeOnGitHub {
            get {
                return ResourceManager.GetString("News.SeeOnGitHub", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Items.
        /// </summary>
        public static string News_Unlockables {
            get {
                return ResourceManager.GetString("News.Unlockables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Watch your achievements turn into items!
        ///The more you play, the more you get!
        ///From backgrounds to game modes, it&apos;s rip and tear until it is done..
        /// </summary>
        public static string News_Unlockables_Description {
            get {
                return ResourceManager.GetString("News.Unlockables.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aspect Ratio.
        /// </summary>
        public static string Settings_AspectRatio {
            get {
                return ResourceManager.GetString("Settings.AspectRatio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintain Proportions.
        /// </summary>
        public static string Settings_AspectRatio_MaintainProportions {
            get {
                return ResourceManager.GetString("Settings.AspectRatio.MaintainProportions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deuteranopia (green-blindness).
        /// </summary>
        public static string Settings_Color_Deuteranopia {
            get {
                return ResourceManager.GetString("Settings.Color.Deuteranopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Original color.
        /// </summary>
        public static string Settings_Color_MaintainColor {
            get {
                return ResourceManager.GetString("Settings.Color.MaintainColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monochromacy.
        /// </summary>
        public static string Settings_Color_Monochromacy {
            get {
                return ResourceManager.GetString("Settings.Color.Monochromacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Protanopia (red-blindness).
        /// </summary>
        public static string Settings_Color_Protanopia {
            get {
                return ResourceManager.GetString("Settings.Color.Protanopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tritanopia (blue-blindness).
        /// </summary>
        public static string Settings_Color_Tritanopia {
            get {
                return ResourceManager.GetString("Settings.Color.Tritanopia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gameplay Screenshots.
        /// </summary>
        public static string Settings_DoomScreenshots {
            get {
                return ResourceManager.GetString("Settings.DoomScreenshots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screenshot Source Blacklist.
        /// </summary>
        public static string Settings_DoomScreenshots_SourceBlacklist {
            get {
                return ResourceManager.GetString("Settings.DoomScreenshots.SourceBlacklist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Follow system.
        /// </summary>
        public static string Settings_Language_FollowSystem {
            get {
                return ResourceManager.GetString("Settings.Language.FollowSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Language:.
        /// </summary>
        public static string Settings_Language_InputFieldPrompt {
            get {
                return ResourceManager.GetString("Settings.Language.InputFieldPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UI.
        /// </summary>
        public static string Settings_UI {
            get {
                return ResourceManager.GetString("Settings.UI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dark Theme.
        /// </summary>
        public static string Settings_UI_DarkTheme {
            get {
                return ResourceManager.GetString("Settings.UI.DarkTheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Use custom theme.
        /// </summary>
        public static string Settings_UI_UseCustomTheme {
            get {
                return ResourceManager.GetString("Settings.UI.UseCustomTheme", resourceCulture);
            }
        }
    }
}
